{"name": "test_1_CreateLog_Click", "status": "broken", "statusDetails": {"message": "AttributeError: 'WebDriver' object has no attribute 'id'", "trace": "self = <testcases.test_create_log.TestCreate_log object at 0x0492DA18>\ntest_logsystem = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"e09a5adf-778e-48ee-96bd-1ae69f3e49e8\")>\n\n    def test_1_CreateLog_Click(self,test_logsystem):\n        self.page1 = TestLogPage(test_logsystem)\n        file = ReadWrite(login_path)\n        userlist = file.read()\n        for user in userlist:\n            self.page1.type_login_email(user[0])\n            self.page1.type_login_pws(user[1])\n            self.page1.click_loginsubm()\n            time.sleep(2)\n        self.page1.click_log()\n        time.sleep(2)\n        self.page1.click_createlog()\n        time.sleep(1)\n        try:\n>           assert self.page1.browser.id ==\"frame_content\"\nE           AttributeError: 'WebDriver' object has no attribute 'id'\n\ntest_create_log.py:22: AttributeError"}, "start": 1628833243685, "stop": 1628833249609, "uuid": "336a1522-c495-40a0-9b4c-c3522c394f8c", "historyId": "491a0f829ae339d87b82b3ba8b3c086b", "testCaseId": "557146b09ecbc7d008868c3d0f32d6d6", "fullName": "testcases.test_create_log.TestCreate_log#test_1_CreateLog_Click", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_create_log"}, {"name": "subSuite", "value": "TestCreate_log"}, {"name": "host", "value": "DESKTOP-S2QKEKE"}, {"name": "thread", "value": "16220-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_create_log"}]}